
name: Cancel

on: [push]

jobs:
  cancel:
    name: "Cancel Previous Runs"
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: styfle/cancel-workflow-action@0.4.1
        with:
          # curl -v -H "Authorization: token XXX" https://api.github.com/repos/menelike/meteor-streamed-joins/actions/workflows
          # 1920965 => .github/workflows/development.yml
          workflow_id: 1920965
          access_token: ${{ github.token }}
